version: '3.8'
services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=production
      volumes:
      - ./:/backend
      - node_modules:/backend/node_modules
      environment:
        - MONGODB_URI=mongodb://shubhamwebdesign:shubhamwebdesign@database:27017/portfolio?authSource=admin
        - PORT=5000
        - PAYLOAD_SECRET=16dd3298d7b59beed42ea21dqwerskv24562b4562bbu3bu
        - SENDGRID_API_KEY=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
        - SERVER_URL=http://backend:5000
      command: yarn start
  database:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shubhamwebdesign
      - MONGO_INITDB_ROOT_PASSWORD=shubhamwebdesign