version: '3.8'
services:
  backend:
    ports:
      - '5000:5000'
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/backend
      - node_modules:/backend/node_modules
    environment:
      - MONGODB_URI=mongodb://shubhamwebdesign:shubhamwebdesign@database:27017?authSource=admin
      - PAYLOAD_SECRET=16dd3298d7b59beed42ea21dqwerskv24562b4562bbu3bu
      - SENDGRID_API_KEY=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
      - PORT=5000
      - SERVER_URL=http://backend:5000
  database:
      environment:
      - MONGO_INITDB_ROOT_USERNAME=shubhamwebdesign
      - MONGO_INITDB_ROOT_PASSWORD=shubhamwebdesign  

volumes:
  database:
  node_modules: