/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  avatar?: string | Media;
  role: 'admin' | 'startup' | 'investor';
  isVerified: '1' | '0';
  otp?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes: {
    thumbnail: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    card: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    tablet: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  icon: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "library".
 */
export interface Library {
  id: string;
  title: string;
  views: number;
  tags?: string[] | Tag[];
  tagline: string;
  'sub-tagline': string;
  blocks: (
    | {
        text: string;
        classname?: string;
        id?: string;
        blockName?: string;
        blockType: 'primary-heading';
      }
    | {
        text: string;
        classname?: string;
        id?: string;
        blockName?: string;
        blockType: 'secondary-heading';
      }
    | {
        text: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'parragraph';
      }
    | {
        code: {
          [k: string]: unknown;
        }[];
        language: 'jsx' | 'json';
        'show-line-numbers'?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'code';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
